### ISSUE TITLE
EW11 configuration

### ISSUE THREAD

**Issue by msnatm** [mvdklip/Domoticz-Hewalex#2]
Hi,

thanks for the extensive explanation and documentation on the hewalex integration.
I am trying to get an EW11 converter to work with my ZPS controller (2nd free port), but I don't get any data from the converter. From the documentation it is not fully clear how the serial setting should be for the protocol (none, frame, modbus).

I have tried many settings on 2 different EW11 converters but without any luck. Would it be possible to add a working EW configuration file to the documentation? I am clueless why the converter is not providing any data from the controller.

Kind regards, Marcel.

**Comment by mvdklip** [comment]
Hi Marcel,

No fancy settings here, just plain serial communication at 38400 baud. Including screenshots for reference:

![Screenshot_20211214-202031](https://user-images.githubusercontent.com/200318/146065653-63576196-2874-4a9d-888d-fae535ac01a2.png)
![Screenshot_20211214-202022](https://user-images.githubusercontent.com/200318/146065668-6bc5ef8e-2654-4307-9cab-bfbd7e2f08da.png)

If that doesn't work then I'd recommend to doublecheck the wiring!


Greets,

Matthijs

**Comment by mvdklip** [comment]
Something else sprang to mind: you are not expecting output from the ZPS without sending a valid command, are you? Because the protocol is binary and is modbus-like (but is not modbus) and the ZPS will only send a reply after you send a command.

**Comment by msnatm** [comment]
Thanks Matthijs for this last remark, I was indeed waiting. I was monitoring the output to the MQTT broker. Initially I had also an ekontrol modem connected but I simplified the connection eventually to only the EW11 and one ZPS controller. I captured only one message during last night which I could not understand. But now I do.

upcoming weekend I will

**Comment by mvdklip** [comment]
Hi Marcel, your name sounds Dutch... Would you be willing to lend me the ekontrol modem for a while? I think it might allow me to reverse engineer the protocol even further.

**Comment by msnatm** [comment]
That is correct Matthijs. We can arrange that, I do use it but the sun is not actively shining this time of year. 
Via the website there are many settings to access which can help you to understand the protocol.

**Comment by mvdklip** [comment]
So are you on this Tweakers.net topic by any chance?

https://gathering.tweakers.net/forum/list_messages/2069540

If not how can I contact you? You can find my contact details at https://www.thelamp.cc
