### ISSUE TITLE
Forcing a defrost cycle somehow possible?

### ISSUE THREAD

**Issue by Alexgrosy** [mvdklip/Domoticz-Hewalex#7]
Hi!
This is not really an issue, but rather a feature request. Has anyone found out if it is somehow possible to force the heatpump go into a defrosting cycle, even if the defrosting interval has not passed yet?
In my setup, I'm measuring the evaporator temperature from the data of the heatpump, and also the exhaust air temperature using a separate temperature sensor.
As long as there is no ice on the evaporator, both temperatures are almost the same. As soon as there is a thick layer of ice, the evaporator temperature will drop rapidly, but the exhaust air temperature stays the same or even increases due to restricted air flow / bad heat conductivity of the ice.
Rather than waiting at least 30 minutes until the defrost interval has passed, I would preferably want to start a defrost cycle if the delta between evaporator temperature and exhaust air temperature is larger than a specific value.
I think using this method the efficiency of the heat pump could be increased quite a bit.
So has anyone found a register which initiates a defrost cycle? :)
best regards!

**Comment by mvdklip** [comment]
Hi Alex,

Why don't you just lower the interval time? Either permanently or temporarily when you detect that a defrost could be beneficial?

To be honest I'm skeptical that this would actually improve efficiency though. Hewalex must have a lot of experience tuning these things. So unless you use the heatpump in a situation it is not meant for (floor heating?) I am not sure you are actually improving things. But you can always try and measure!

**Comment by mvdklip** [comment]
Ah... Just saw that the minimum interval is 30 mins. In that case I don't have a solution.

Manual says this by the way:

_Defrosting cycle start-up delay function allows setting time within interval: 30-90min. If there is no delay, below temperature activating defrosting heat pump would be continuously in defrosting mode._

Looks like it tries to explain why the delay is present.

**Comment by Alexgrosy** [comment]
Hi!
Unfortunately, the shortest interval is 30 minutes. And yes, I'm using the heatpump for floor heating with very low hot water temperatures of usually < 35 °C. That's why I also have more problems with ice than in regular use.

I know why the delay is present, but in my case I would rather prefer to set the delay to infinity, and defrost depending on the temperatures. Right now, I have this issue again. You can see it in my measuring chart. Actually defrosting should occur independent of any delay, but when the temperature difference between the evaporator and the exhaust air increases and the thermal power of the heat pump decreases, if you know what I mean :)
![Messung](https://github.com/mvdklip/Domoticz-Hewalex/assets/93903795/8bc4760f-5239-417a-96fd-a46e87852d5b)

That's why it would be cool to know if there is any chance to force a defrost cycle in this heatpump using some register.

**Comment by mvdklip** [comment]
I am fairly sure it is not possible to force a defrost through a register. This because the communication protocol doesn't allow for sending commands to the executive module. The controller can only read status registers and read/write config registers. So if it is possible to force a defrost then only by somehow 'tricking' the executive module into starting one by changing the defrosting config.

**Comment by mvdklip** [comment]
One more idea: have you played around with the "manual control"? Is there something in there to start a defrost?

**Comment by Alexgrosy** [comment]
Just checked, unfortunately no option to start a defrost, only some relay controls :(
then probably no chance other than to wait the 30 minutes defrost delay...

**Comment by mvdklip** [comment]
Another idea: there might be a register containing the current timer value ticking towards the defrosting delay. You'd have to debug this yourselves during a defrost delay by dumping the contents of yet unknown registers and seeing whether there is one which normally holds 0 but is ticking up or down during the defrosting delay. One problem though: even if you find the register holding this value it is probably a status register which you can't overwrite. In the off change it is a config register instead you could probably trick the heatpump by overwriting the value.

**Comment by Alexgrosy** [comment]
Can't find anything suspicious... I'm probably going to rip out the original controller and make one myself. This is I guess faster and easier than messing around with the original firmware.
Thank you anyway!
